const { Stack }  = require('./stack.js')

const stack = new Stack()
console.log(stack, 'stackstack')
console.log(stack.isEmpty())
stack.push(1)
stack.push(2)
stack.push(3)
stack.push(4)
console.log(stack.peek())
stack.pop()
console.log(stack.peek())
console.log(stack.toString())